base:
  image: ubuntu:24.04
  config: rwx/base 1.0.0

tasks:
  - key: code
    call: git/clone 2.0.0
    with:
      repository: https://github.com/rwx-cloud/language-server.git
      github-token: ${{ github['rwx-cloud'].token }}
      ref: ${{ init.ref }}

  - key: tool-versions
    use: [code]
    call: rwx/tool-versions 1.0.6

  - key: node
    call: nodejs/install 1.1.11
    with:
      node-version: ${{ tasks.tool-versions.values.nodejs }}

  - key: npm-install
    use: [node, code]
    run: npm install
    filter:
      - package.json
      - package-lock.json

  - key: build
    use: npm-install
    run: npm run bundle
    filter:
      - node_modules
      - src
      - support
      - package*.json
      - tsconfig*
    outputs:
      artifacts:
        - key: bundle
          path: dist/server.js

  - key: test-bundle
    use: build
    run: node ${{ run.dir }}/test-bundle.js
